src/packaged/main/domain/objects/ContractSchedule__c/ContractSchedule__c.object-meta.xml
<CustomObject>
    <description>A fake contract schedule to stress database a little.</description>
    <label>Contract Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Contract Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/domain/objects/ContractSchedule__c/fields/ServiceContract__c.field-meta.xml
<CustomField>
    <fullName>ServiceContract__c</fullName>
    <description></description>
    <inlineHelpText></inlineHelpText>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Contract Schedules</relationshipLabel>
    <relationshipName>ContractSchedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/packaged/main/domain/objects/ServiceContract/fields/Schedules__c.field-meta.xml
<CustomField>
    <fullName>Schedules__c</fullName>
    <label>Schedules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/default/classes/ServiceContractFactory.cls
public class ServiceContractFactory {
    public static List<ServiceContractDecorator> make(List<Id> recordIds) {
        Map<Id, ServiceContract> scs = new Map<Id, ServiceContract>(
            [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract WHERE Id IN :recordIds]
        );
        List<ServiceContractDecorator> decs = new List<ServiceContractDecorator>();
        for (Id contractId : recordIds) {
            decs.add(new ServiceContractDecorator(scs.get(contractId), scs.get(contractId).ContractSchedules__r));
        }
        return decs;
    }
}