src/packaged/main/domain/objects/ContractSchedule__c/ContractSchedule__c.object-meta.xml
<CustomObject>
    <description>A fake contract schedule to stress database a little.</description>
    <label>Contract Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Contract Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/domain/objects/ContractSchedule__c/fields/ServiceContract__c.field-meta.xml
<CustomField>
    <fullName>ServiceContract__c</fullName>
    <description></description>
    <inlineHelpText></inlineHelpText>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Contract Schedules</relationshipLabel>
    <relationshipName>ContractSchedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/packaged/main/domain/objects/ServiceContract/fields/Schedules__c.field-meta.xml
<CustomField>
    <fullName>Schedules__c</fullName>
    <label>Schedules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/test/classes/Test_E2E_ProductUse10.cls
@isTest
public class Test_E2E_ProductUse10 {
    @TestSetup
    static void makeData() {
        TestFixtures.InsertProductsWithStandardPrices();
        List<Account> accs = TestFixtures.InsertFullServiceContractStructure(Test.getStandardPricebookId(), 25);
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated1() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated2() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated3() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated4() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated5() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated6() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated7() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated8() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated9() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }

    @isTest
    static void setSchedules_IterateCount_SchedulesCreated10() {
        // ARRANGE
        List<ServiceContract> scs = [SELECT Id FROM ServiceContract];
        // ACT
        Test.startTest();
        for (Integer i = 0; i < scs.size(); i++) {
            scs[i].Schedules__c = i;
        }
        update scs;
        Test.stopTest();
        // ARRANGE
        for (ServiceContract sc : [SELECT Id, Schedules__c, (SELECT Id FROM ContractSchedules__r) FROM ServiceContract]) {
            System.assertEquals(sc.Schedules__c, sc.ContractSchedules__r.size());
        }
    }
}