src/packaged/main/domain/objects/ContractSchedule__c/ContractSchedule__c.object-meta.xml
<CustomObject>
    <description>A fake contract schedule to stress database a little.</description>
    <label>Contract Schedule</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{00000000}</displayFormat>
        <label>Contract Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/domain/objects/ServiceContract/fields/Schedules__c.field-meta.xml
<CustomField>
    <fullName>Schedules__c</fullName>
    <label>Schedules</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/domain/classes/ServiceContractDomain.cls
public class ServiceContractDomain {
    public static void alignSchedules(Set<Id> recordIds) {
        List<ContractSchedule__c> obsoleteSchedules = new List<ContractSchedule__c>();
        List<ContractSchedule__c> newSchedules = new List<ContractSchedule__c>();
        List<ServiceContractDecorator> contracts = ServiceContractFactory.make(new List<Id>(recordIds));
        for (ServiceContractDecorator dec : contracts) {
            ServiceContractDecorator.ContractScheduleResult result = dec.makeSchedules();
            obsoleteSchedules.addAll(result.obsoleteSchedules);
            newSchedules.addAll(result.newSchedules);
        }
        delete obsoleteSchedules;
        insert newSchedules;
    }

    public static void cleanFields(List<ServiceContract> triggerNew) {
        for (ServiceContract sc : triggerNew) {
            if (sc.Schedules__c == null) {
                sc.Schedules__c = 0;
            }
        }
    }
}