src/packaged/main/domain/objects/Product2/fields/AutomaticRenewal__c.field-meta.xml
<CustomField>
    <fullName>AutomaticRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to automatically renew contract line items (recalculating the end date) once they expire.</description>
    <inlineHelpText>If true, line items of this product are automatically renewed when their end date surpasses the cancellation period (they expire).</inlineHelpText>
    <label>Automatic Renewal</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/BillingCycle__c.field-meta.xml
<CustomField>
    <fullName>BillingCycle__c</fullName>
    <description>Controls the periodicity of billing for recurring payments</description>
    <inlineHelpText>Sets the duration of the billing period and therefore, how often this product is billed.</inlineHelpText>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/BillingMode__c.field-meta.xml
<CustomField>
    <fullName>BillingMode__c</fullName>
    <description>Defines how line items using this product are billed.</description>
    <inlineHelpText>Select when line items of this product are billed. As of today, the system only support Advance billing mode.</inlineHelpText>
    <label>Billing Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Arrears</fullName>
                <isActive>false</isActive>
                <label>Arrears</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/DescriptionFormatted__c.field-meta.xml
<CustomField>
    <fullName>DescriptionFormatted__c</fullName>
    <description>Rich text area to store formatted product description text.</description>
    <inlineHelpText>Enter and format text for the product description.</inlineHelpText>
    <label>Formatted Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/ImageLink__c.field-meta.xml
<CustomField>
    <fullName>ImageLink__c</fullName>
    <description>Direct Link to the Image when hosted on external site</description>
    <inlineHelpText>Enter the direct link to the Product&apos;s image. URL can point to internally stored files or external files.</inlineHelpText>
    <label>Image Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/LineItemDateValidationMode__c.field-meta.xml
<CustomField>
    <fullName>LineItemDateValidationMode__c</fullName>
    <description>Configures the validation mode for start/end date of contract line items. Validation is implemented in validation rules on contract line items.</description>
    <inlineHelpText>Select the validation mode that is applied to contract line items, if they use the product. Any Day allows a start in any day of the month and is billed pro rata per day. Full month allows only start at the beginning of month and is billed pro rata full month.</inlineHelpText>
    <label>Line Item Date Validation Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Month</fullName>
            </value>
            <value>
                <fullName>Any Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/MinimumContractTerm__c.field-meta.xml
<CustomField>
    <fullName>MinimumContractTerm__c</fullName>
    <description>The minimum contract term, when this product is used. Calculates the minimum duration (start/end date) of line items.</description>
    <inlineHelpText>Sets the initial duration (start date to end date) for newly created contract line items.</inlineHelpText>
    <label>Minimum Contract Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>24 months</fullName>
            </value>
            <value>
                <fullName>60 months</fullName>
            </value>
            <value>
                <fullName>96 months</fullName>
            </value>
            <value>
                <fullName>Lifetime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/RenewalTerm__c.field-meta.xml
<CustomField>
    <fullName>RenewalTerm__c</fullName>
    <description>Subscription renewal term in months, used to calculate the next end date after renewal.</description>
    <inlineHelpText>The renewal duration months. Each time, a contract line item is automatically renewed, the number of months is added to the end date.</inlineHelpText>
    <label>Renewal Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>A simple status field that extends the basic checkbox functionality and allows to filter in quote product picker.</description>
    <inlineHelpText>Select the product&apos;s status in it&apos;s approval process</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Outdated</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/TerminationPeriod__c.field-meta.xml
<CustomField>
    <fullName>TerminationPeriod__c</fullName>
    <description>The termination period that applies to all contract line items that use this product.</description>
    <inlineHelpText>Set the notice period for terminating contract line items of this product. Used to calculate the renewal date and the end date, if the position is terminated.</inlineHelpText>
    <label>Termination Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines the fundamental behavior of the product during billing, quoting, etc.</description>
    <inlineHelpText>Controls the processing behavior of the product: Base products are billed in Weclapp, while subscription products are billed in Salesforce.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

src/packaged/main/domain/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Base Product</fullName>
        <default>true</default>
        <label>Base Product</label>
    </customValue>
    <customValue>
        <fullName>Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <description>Controls the processing behavior of products</description>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

src/packaged/main/test/classes/Test_E2E_ProductUpdates4.cls
@isTest
public class Test_E2E_ProductUpdates4 {
    private static final String PRICEBOOK_NAME = 'Product Validation PB 4';

    @TestSetup
    static void makeData() {
        TestFixtures.InsertProductsWithCustomPrices(PRICEBOOK_NAME);
    }

    @isTest
    public static void updateBaseProduct_ChangeIrrelevantFields_UpdateSuccessful() {
        // ACT
        Product2 baseProduct = [SELECT Id FROM Product2 WHERE Type__c = 'Base Product' LIMIT 1];
        baseProduct.Name = 'Test Name New';
        baseProduct.ProductCode = 'PC-1';
        baseProduct.ImageLink__c = 'https://mobilityhouse.com/random-image.png';
        baseProduct.Description = 'Description';
        baseProduct.DescriptionFormatted__c = '<p>Formatted</p>';
        baseProduct.Status__c = 'Active';
        Database.SaveResult sr = Database.update(baseProduct);
        // ASSERT
        System.assertEquals(true, sr.isSuccess(), 'is success: ' + sr.getErrors());
    }

    @isTest
    public static void updateSubscriptionProduct_ChangeIrrelevantFields_UpdateSuccessful() {
        // ACT
        Product2 subscriptionProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'B-1'];
        subscriptionProduct.Name = 'Test Name New';
        subscriptionProduct.ProductCode = 'PC-1';
        subscriptionProduct.Status__c = 'Active';
        subscriptionProduct.RenewalTerm__c = 1;
        subscriptionProduct.MinimumContractTerm__c = '12 months';
        subscriptionProduct.TerminationPeriod__c = '1 month';
        Database.update(subscriptionProduct);
        // ASSERT
        subscriptionProduct = [
            SELECT Id, RenewalTerm__c, MinimumContractTerm__c, TerminationPeriod__c
            FROM Product2
            WHERE Id = :subscriptionProduct.Id
        ];
        System.assertEquals(1, subscriptionProduct.RenewalTerm__c, 'renewal term updated');
        System.assertEquals('12 months', subscriptionProduct.MinimumContractTerm__c, 'minimum contract term updated');
        System.assertEquals('1 month', subscriptionProduct.TerminationPeriod__c, 'minimum contract term updated');
    }

    @isTest
    public static void updateType_ToBaseProduct_CanNotBeUpdated() {
        // ACT
        Product2 subscriptionProduct = [SELECT Id FROM Product2 WHERE Type__c = 'Subscription' LIMIT 1];
        subscriptionProduct.Type__c = 'Base Product';
        // just set to null so other validation rules don't fire
        subscriptionProduct.BillingCycle__c = null;
        subscriptionProduct.AutomaticRenewal__c = false;
        subscriptionProduct.MinimumContractTerm__c = null;
        subscriptionProduct.RenewalTerm__c = null;
        subscriptionProduct.QuantityUnitOfMeasure = 'Each';
        subscriptionProduct.LineItemDateValidationMode__c = null;
        subscriptionProduct.BillingMode__c = null;
        subscriptionProduct.TerminationPeriod__c = null;
        Database.SaveResult sr = Database.update(subscriptionProduct, false);
        // ASSERT
        System.assertEquals(false, sr.isSuccess(), 'update successful');
        System.assertEquals(
            System.StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION,
            sr.getErrors()[0].getStatusCode(),
            'first error is custom validation: ' + sr.getErrors()
        );
    }

    @isTest
    public static void updateType_ToSubscription_CanNotBeUpdated() {
        // ACT
        Product2 baseProduct = [SELECT Id FROM Product2 WHERE Type__c = 'Base Product' LIMIT 1];
        baseProduct.Type__c = 'Subscription';
        // set valid values, so unrelated validation rules don't fire
        baseProduct.BillingCycle__c = 'Yearly';
        baseProduct.AutomaticRenewal__c = true;
        baseProduct.MinimumContractTerm__c = '12 months';
        baseProduct.RenewalTerm__c = 12;
        baseProduct.QuantityUnitOfMeasure = 'Each';
        baseProduct.LineItemDateValidationMode__c = 'Full Month';
        baseProduct.BillingMode__c = 'Advance';
        baseProduct.TerminationPeriod__c = '3 months';
        Database.SaveResult sr = Database.update(baseProduct, false);
        // ASSERT
        System.assertEquals(false, sr.isSuccess(), 'update successful');
        System.assertEquals(
            System.StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION,
            sr.getErrors()[0].getStatusCode(),
            'first error is custom validation: ' + sr.getErrors()
        );
    }

    @isTest
    public static void updateBillingCycle_Monthly_CanNotBeUpdated() {
        // ACT
        Product2 subscriptionProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'B-1' LIMIT 1];
        subscriptionProduct.BillingCycle__c = 'Monthly';
        Database.SaveResult sr = Database.update(subscriptionProduct, false);
        // ASSERT
        System.assertEquals(false, sr.isSuccess(), 'update successful');
        System.assertEquals(
            System.StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION,
            sr.getErrors()[0].getStatusCode(),
            'first error is custom validation: ' + sr.getErrors()
        );
    }

    @isTest
    public static void updateAutomaticRenewal_Deactivate_CanNotBeUpdated() {
        // ACT
        Product2 subscriptionProduct = [SELECT Id FROM Product2 WHERE ProductCode = 'B-1' LIMIT 1];
        subscriptionProduct.AutomaticRenewal__c = false;
        subscriptionProduct.RenewalTerm__c = null;
        Database.SaveResult sr = Database.update(subscriptionProduct, false);
        // ASSERT
        System.assertEquals(false, sr.isSuccess(), 'update successful');
        System.assertEquals(
            System.StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION,
            sr.getErrors()[0].getStatusCode(),
            'first error is custom validation: ' + sr.getErrors()
        );
    }
}