src/packaged/main/domain/objects/Product2/fields/AutomaticRenewal__c.field-meta.xml
<CustomField>
    <fullName>AutomaticRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to automatically renew contract line items (recalculating the end date) once they expire.</description>
    <inlineHelpText>If true, line items of this product are automatically renewed when their end date surpasses the cancellation period (they expire).</inlineHelpText>
    <label>Automatic Renewal</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/BillingCycle__c.field-meta.xml
<CustomField>
    <fullName>BillingCycle__c</fullName>
    <description>Controls the periodicity of billing for recurring payments</description>
    <inlineHelpText>Sets the duration of the billing period and therefore, how often this product is billed.</inlineHelpText>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One Time</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/BillingMode__c.field-meta.xml
<CustomField>
    <fullName>BillingMode__c</fullName>
    <description>Defines how line items using this product are billed.</description>
    <inlineHelpText>Select when line items of this product are billed. As of today, the system only support Advance billing mode.</inlineHelpText>
    <label>Billing Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance</fullName>
            </value>
            <value>
                <fullName>Arrears</fullName>
                <isActive>false</isActive>
                <label>Arrears</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/LineItemDateValidationMode__c.field-meta.xml
<CustomField>
    <fullName>LineItemDateValidationMode__c</fullName>
    <description>Configures the validation mode for start/end date of contract line items. Validation is implemented in validation rules on contract line items.</description>
    <inlineHelpText>Select the validation mode that is applied to contract line items, if they use the product. Any Day allows a start in any day of the month and is billed pro rata per day. Full month allows only start at the beginning of month and is billed pro rata full month.</inlineHelpText>
    <label>Line Item Date Validation Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Month</fullName>
            </value>
            <value>
                <fullName>Any Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/MinimumContractTerm__c.field-meta.xml
<CustomField>
    <fullName>MinimumContractTerm__c</fullName>
    <description>The minimum contract term, when this product is used. Calculates the minimum duration (start/end date) of line items.</description>
    <inlineHelpText>Sets the initial duration (start date to end date) for newly created contract line items.</inlineHelpText>
    <label>Minimum Contract Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>24 months</fullName>
            </value>
            <value>
                <fullName>60 months</fullName>
            </value>
            <value>
                <fullName>96 months</fullName>
            </value>
            <value>
                <fullName>Lifetime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/RenewalTerm__c.field-meta.xml
<CustomField>
    <fullName>RenewalTerm__c</fullName>
    <description>Subscription renewal term in months, used to calculate the next end date after renewal.</description>
    <inlineHelpText>The renewal duration months. Each time, a contract line item is automatically renewed, the number of months is added to the end date.</inlineHelpText>
    <label>Renewal Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/TerminationPeriod__c.field-meta.xml
<CustomField>
    <fullName>TerminationPeriod__c</fullName>
    <description>The termination period that applies to all contract line items that use this product.</description>
    <inlineHelpText>Set the notice period for terminating contract line items of this product. Used to calculate the renewal date and the end date, if the position is terminated.</inlineHelpText>
    <label>Termination Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/domain/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines the fundamental behavior of the product during billing, quoting, etc.</description>
    <inlineHelpText>Controls the processing behavior of the product: Base products are billed in Weclapp, while subscription products are billed in Salesforce.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

src/packaged/main/domain/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Base Product</fullName>
        <default>true</default>
        <label>Base Product</label>
    </customValue>
    <customValue>
        <fullName>Subscription</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <description>Controls the processing behavior of products</description>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

src/packaged/main/test/classes/TestFixtures.cls
@isTest
public class TestFixtures {
    public static List<Account> InsertDefaultAccounts() {
        List<Account> accs = new List<Account>();
        accs.add(CreateAccount('Test GmbH 1', '1000'));
        accs.add(CreateAccount('Lieferanten Test GmbH 1', '1001'));
        accs.add(CreateAccount('Kunden Test AG 1', '1002'));
        insert accs;
        return accs;
    }

    public static List<Account> InsertFullOrderStructure(Id pricebookId) {
        return InsertFullOrderStructure(pricebookId, 3);
    }

    public static List<Account> InsertFullOrderStructure(Id pricebookId, Integer orderCount) {
        List<Account> customers = InsertDefaultAccounts();
        List<Order> orders = new List<Order>();
        for (Integer i = 0; i < orderCount; i++) {
            orders.add(CreateOrder('Test Order ' + i, customers[0].Id, pricebookId));
        }
        insert orders;
        if (pricebookId != null) {
            List<OrderItem> items = new List<OrderItem>();
            for (Order o : orders) {
                items.addAll(createOrderItems(o.Id, [SELECT Id, UnitPrice FROM PricebookEntry WHERE Pricebook2Id = :pricebookId]));
            }
            insert items;
        }
        return customers;
    }

    public static List<Account> InsertFullServiceContractStructure(Id pricebookId) {
        List<Account> customers = InsertDefaultAccounts();
        List<ServiceContract> contracts = new List<ServiceContract>();
        contracts.add(CreateServiceContract('Test Contract 1', customers[0].Id, pricebookId));
        contracts.add(CreateServiceContract('Test Contract 2', customers[0].Id, pricebookId));
        contracts.add(CreateServiceContract('Test Contract 3', customers[0].Id, pricebookId));
        insert contracts;
        if (pricebookId != null) {
            List<ContractLineItem> items = new List<ContractLineItem>();
            for (ServiceContract sc : contracts) {
                items.addAll(createContractLineItems(sc.Id, [SELECT Id, UnitPrice FROM PricebookEntry WHERE Pricebook2Id = :pricebookId]));
            }
            insert items;
        }
        return customers;
    }

    public static Pricebook2 InsertProductsWithCustomPrices(String pricebookName) {
        List<Product2> prods = InsertProductsWithStandardPrices();
        // return AddProductsToCustomPricebook(pricebookName, 120, prods);
        Pricebook2 pb = new Pricebook2(Id = Test.getStandardPricebookId());
        update pb;
        return pb;
    }

    public static Pricebook2 AddProductsToCustomPricebook(String pricebookName, Decimal unitPrice, List<Product2> products) {
        Pricebook2 customPricebook = CreatePricebook(pricebookName);
        insert customPricebook;
        List<PricebookEntry> prices = new List<PricebookEntry>();
        for (Product2 prod : products) {
            prices.add(new PricebookEntry(Pricebook2Id = customPricebook.Id, Product2Id = prod.Id, UnitPrice = unitPrice, IsActive = true));
        }
        insert prices;
        return customPricebook;
    }

    public static List<Product2> InsertProductsWithStandardPrices() {
        List<Product2> prods = CreateDefaultProducts();
        insert prods;
        InsertStandardPrices(prods);
        return prods;
    }

    public static List<Product2> CreateDefaultProducts() {
        List<Product2> prods = new List<Product2>();
        for (Integer i = 0; i < 100; i++) {
            String prodName = 'Test Base Product {0}';
            String prodCode = 'A-{0}';
            prods.add(
                CreateProduct(
                    String.format(prodName, new List<Object>{ i }),
                    String.format(prodCode, new List<Object>{ i }),
                    'Base Product',
                    'Each'
                )
            );
        }
        for (Integer i = 0; i < 100; i++) {
            String prodName = 'Test Subscription Product {0}';
            String prodCode = 'B-{0}';
            prods.add(
                CreateSubscriptionProduct(
                    String.format(prodName, new List<Object>{ i }),
                    String.format(prodCode, new List<Object>{ i }),
                    'Yearly',
                    '12 months'
                )
            );
        }
        return prods;
    }

    public static Account CreateAccount(String accountName, String accountNumber) {
        return new Account(
            Name = accountName,
            AccountNumber = accountNumber,
            BillingStreet = 'Karlstraße 1',
            BillingPostalCode = '86152',
            BillingCity = 'Augsburg',
            BillingCountryCode = 'DE'
        );
    }

    public static ServiceContract CreateServiceContract(String contractName, Id accountId, Id pricebookId) {
        return new ServiceContract(
            Name = contractName,
            StartDate = System.today(),
            Pricebook2Id = pricebookId,
            AccountId = accountId,
            BillingStreet = 'Straße 1',
            BillingPostalCode = '12345',
            BillingCity = 'Berlin',
            BillingCountryCode = 'DE',
            ShippingStreet = 'Straße 1',
            ShippingPostalCode = '12345',
            ShippingCity = 'Berlin',
            ShippingCountryCode = 'DE'
        );
    }

    public static Order CreateOrder(String orderName, Id accountId, Id pricebookId) {
        return new Order(
            Name = orderName,
            EffectiveDate = System.today(),
            Pricebook2Id = pricebookId,
            AccountId = accountId,
            Status = 'Draft',
            BillingStreet = 'Straße 1',
            BillingPostalCode = '12345',
            BillingCity = 'Berlin',
            BillingCountryCode = 'DE',
            ShippingStreet = 'Straße 1',
            ShippingPostalCode = '12345',
            ShippingCity = 'Berlin',
            ShippingCountryCode = 'DE'
        );
    }

    public static Pricebook2 CreatePricebook(String pricebookName) {
        return new Pricebook2(Name = pricebookName, IsActive = true);
    }

    public static Product2 CreateProduct(String productName, String productCode, String productType, String unit) {
        return new Product2(
            Name = productName,
            ExternalId = productCode,
            ProductCode = productCode,
            Family = productType,
            Type__c = productType,
            QuantityUnitOfMeasure = unit,
            IsActive = true
        );
    }

    public static Product2 CreateSubscriptionProduct(String productName, String productCode, String billingCycle, String terms) {
        Product2 prod = CreateProduct(productName, productCode, 'Subscription', null);
        prod.BillingCycle__c = billingCycle;
        prod.AutomaticRenewal__c = true;
        prod.MinimumContractTerm__c = terms;
        prod.RenewalTerm__c = 12;
        prod.QuantityUnitOfMeasure = billingCycle == 'Yearly' ? 'per Year' : 'per Month';
        prod.LineItemDateValidationMode__c = billingCycle == 'Yearly' ? 'Full Month' : 'Any Day';
        prod.BillingMode__c = 'Advance';
        prod.TerminationPeriod__c = '3 months';
        return prod;
    }

    public static Product2 CreateSubscriptionProduct(
        String productName,
        String productCode,
        String billingCycle,
        String terms,
        Boolean automaticRenewal
    ) {
        Product2 prod = CreateSubscriptionProduct(productName, productCode, billingCycle, terms);
        prod.AutomaticRenewal__c = automaticRenewal;
        prod.RenewalTerm__c = automaticRenewal ? 12 : null;
        return prod;
    }

    private static List<OrderItem> createOrderItems(Id orderId, List<PricebookEntry> pricebookEntries) {
        List<OrderItem> orderItems = new List<OrderItem>();
        for (PricebookEntry pbe : pricebookEntries) {
            orderItems.add(new OrderItem(OrderId = orderId, PricebookEntryId = pbe.Id, Quantity = 3, UnitPrice = pbe.UnitPrice));
        }
        return orderItems;
    }

    private static List<ContractLineItem> createContractLineItems(Id contractId, List<PricebookEntry> pricebookEntries) {
        List<ContractLineItem> clis = new List<ContractLineItem>();
        for (PricebookEntry pbe : pricebookEntries) {
            clis.add(
                new ContractLineItem(ServiceContractId = contractId, PricebookEntryId = pbe.Id, Quantity = 5, UnitPrice = pbe.UnitPrice)
            );
        }
        return clis;
    }

    private static List<PricebookEntry> InsertStandardPrices(List<Product2> products) {
        List<PricebookEntry> prices = new List<PricebookEntry>();
        for (Product2 prod : products) {
            prices.add(
                new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = prod.Id, UnitPrice = 100, IsActive = true)
            );
        }
        insert prices;
        return prices;
    }
}